Fix distro version check in 20_unconfined
beaker-project/restraint pull request #180
Opened 2021-02-03 18:16 UTC by WOnder93

First, on Rawhide fedora-release no longer provides redhat-release (I
mean why should it, really?), so try redhat-release first and then
fedora-release.

Second, the distro family wasn't actually being compared - fix that,
too.

And finally, add quotes where appropriate in this function and refactor
the flow a bit.

Closes: BKR-5033

2021-02-04 18:37 UTC, cbouchar commented
Please add "Closes: BKR-5033" to the end of your commit message.

2021-02-04 19:09 UTC, WOnder93 commented
@cbouchar Done.

2021-02-04 21:46 UTC, cbouchar requested changes
I've gone through the code with a fine tooth comb and it looks good.  It will require a release note created by reno.

2021-02-04 21:49 UTC, cbouchar commented
/packit

2021-02-04 22:07 UTC, WOnder93 commented
An interesting tool... I hope I did it right :)

2021-02-08 13:09 UTC, renanrodrigo commented
/packit build

2021-02-08 15:27 UTC, cbouchar commented
> An interesting tool... I hope I did it right :)

It's a tool also used in Openstack for same purpose.  It makes it easier to collect release notes in one sweep instead of
trying to write them all at the end.  Thank you for doing this.

2021-02-08 15:27 UTC, cbouchar approved these changes

2021-02-11 19:11 UTC, merged