Update systemd OOMPolicy for restraintd so it will continue to run
beaker-project/restraint pull request #226
Opened 2021-06-21 15:59 UTC by p3ck

This change keeps restraintd from being oomkilled and since some testing
requires pushing the system into oomkill it's important to not kill the
test runner.

Fixes #224

Change-Id: Iec26c7b00761196a3a2491ba9f8802268283821c

2021-06-21 16:00 UTC, p3ck commented
These needs to be verified against older releases of RHEL/systemd to make sure this option doesn't cause an unknown syntax error.

2021-06-21 16:24 UTC, StykMartin commented
```
[/usr/lib/systemd/system/postfix.service:15] Unknown lvalue 'OOMPolicy' in section 'Service'
[martin@blackhole ~]$ cat /etc/*release
CentOS Linux release 7.8.2003 (Core)
```

2021-06-21 16:50 UTC, StykMartin requested changes
- RHEL 7 not supported (systemd v219)
- RHEL 8 not supported (systemd v239) 
- Support starts with Fedora 31 (systemd v243)

Based on the tags in systemd project it seems they added support for this in v243 RC.

So, we can get support for all Fedoras + RHEL9 regarding this, if we make it conditional. Not sure if it is the target audience.

Thoughts @p3ck ?

2021-06-21 19:25 UTC, p3ck commented
Ok.  So my thought is to have a service file for rhel7 and 8 and then a
default one going forward.  This way when rhel7 and 8 finally drop off we
can just remove the legacy bits and allow the new default to go through.

I can work on an updated patch.

On Mon, Jun 21, 2021 at 12:50 PM Martin ***@***.***> wrote:

> *@StykMartin* requested changes on this pull request.
>
>    - RHEL 7 not supported (systemd v219)
>    - RHEL 8 not supported (systemd v239)
>    - Support starts with Fedora 31 (systemd v243)
>
> Based on the tags in systemd project it seems they added support for this
> in v243 RC.
>
> So, we can get support for all Fedoras + RHEL9 regarding this, if we make
> it conditional. Not sure if it is the target audience.
>
> Thoughts @p3ck <https://github.com/p3ck> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/beaker-project/restraint/pull/226#pullrequestreview-688662892>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUPZOFBZSZ4Q2NTH5EAMQLTT5UVBANCNFSM47B3ZFUQ>
> .
>

2021-06-22 10:48 UTC, StykMartin commented
/packit build

2021-06-23 19:35 UTC, cbouchar reviewed
Before I approve, I wanted to voice my concern about copying files when I wonder if there a better way to do this without doing a file copy?  Copying files is maintenance accident ready to happen.  Is it possible to do an 'sed' operation on the file and pop a line beneath OOMScoreAdjust or some kind of substitution?

2021-06-23 19:50 UTC, p3ck commented
My opinion is that it's more complicated to create a sed command.  I understand your concern with having an almost duplicate file but it's pretty clear when you see the two files in the same directory.  One is called -legacy and you can easily diff them.  But I would have to dig into the Makefile or worse, in the spec file to see a sed command.

2021-06-23 20:19 UTC, cbouchar commented
> i

The following would do the trick.  I'm just throwing it out there.  I'm really not fond of duplicating code.
Let's let Martin chime in.  
%if 0%{?fedora} || 0%{?rhel} >= 9
sed -i '/OOMScoreAdjust=-1000/ a OOMPolicy=continue' init.d/restraintd.service
%endif
make DESTDIR=%{buildroot} install

2021-06-26 01:38 UTC, daniellutz approved these changes
👍🏻

2021-06-28 07:04 UTC, StykMartin approved these changes
I don't have any problems with this implementation. All looks good. Make by default will use restraintd. service file and developer can swap for -legacy if needed. This is quite clear from Makefile. Of course, we could implement this as sed or something like this in specfile, however, this would result in inconsistency. Specfile creating different packages as we can see in VCS.

2021-06-29 12:42 UTC, cbouchar approved these changes

2021-06-29 18:28 UTC, merged